# Model Configuration
d_model: 128
num_heads: 4
d_ff: 512
num_layers: 2
max_seq_len: 128
dropout: 0.1
use_positional_encoding: true
model_type: encoder_only

# Training Configuration - 优化用于快速实验
batch_size: 16
learning_rate: 0.002  # 提高学习率
weight_decay: 0.01
num_epochs: 8         # 减少轮次
random_seed: 42

# Experiment Configuration
experiment_name: "fast_ablation"
save_interval: 4      # 更频繁保存